import {
  GOOGLE_GEO_TARGET_IDS,
  RADIO_MAXIMO_KM,
  RADIO_MINIMO_KM,
} from "./constructor";

export { RADIO_MAXIMO_KM, RADIO_MINIMO_KM };

/**
 * Metadata de mapa para los países que el selector de ubicaciones puede
 * ofrecer — exactamente los que ya tienen id de destino geográfico de
 * Google verificado en `GOOGLE_GEO_TARGET_IDS` (los 219 países activos de la
 * tabla oficial de Google). Un país sin ese id se quedaría marcado en el
 * mapa pero sin poder segmentarlo de verdad en Google, así que la lista
 * nace de esa tabla en vez de mantenerse aparte.
 *
 * `iso3` es la clave que trae el GeoJSON de fronteras en
 * `/public/geo/world-countries.json` (ese archivo usa ISO-3166-1 alfa-3,
 * no alfa-2) — verificado contra `i18n-iso-countries` (datos ISO 3166-1
 * oficiales), no inventado. `lat`/`lng` son el centro geográfico
 * aproximado (el centro del recuadro que ocupa el país en ese mismo
 * GeoJSON), solo para centrar y hacer zoom en el mapa — no viajan a
 * ninguna plataforma; lo que de verdad segmenta es el código ISO alfa-2
 * (Meta) o el id de Google. `null` en los ~50 territorios y microestados
 * que ese GeoJSON simplificado no incluye (Andorra, Singapur, Mónaco...):
 * siguen siendo países segmentables reales, solo sin centro para el mapa.
 */
const METADATA: Record<string, { iso3: string; label: string; lat: number | null; lng: number | null }> = {
  AF: { iso3: "AFG", label: "Afganistán", lat: 33.9, lng: 67.84 },
  AL: { iso3: "ALB", label: "Albania", lat: 41.16, lng: 20.16 },
  DE: { iso3: "DEU", label: "Alemania", lat: 51.14, lng: 10.5 },
  AD: { iso3: "AND", label: "Andorra", lat: null, lng: null },
  AO: { iso3: "AGO", label: "Angola", lat: -11.18, lng: 17.86 },
  AQ: { iso3: "ATA", label: "Antártida", lat: -74.44, lng: 0.03 },
  AG: { iso3: "ATG", label: "Antigua y Barbuda", lat: null, lng: null },
  SA: { iso3: "SAU", label: "Arabia Saudita", lat: 24.25, lng: 45.15 },
  DZ: { iso3: "DZA", label: "Argelia", lat: 28.09, lng: 1.66 },
  AR: { iso3: "ARG", label: "Argentina", lat: -38.54, lng: -63.52 },
  AM: { iso3: "ARM", label: "Armenia", lat: 39.99, lng: 45.04 },
  AU: { iso3: "AUS", label: "Australia", lat: -27.15, lng: 133.45 },
  AT: { iso3: "AUT", label: "Austria", lat: 47.74, lng: 13.23 },
  AZ: { iso3: "AZE", label: "Azerbaiyán", lat: 40.07, lng: 47.59 },
  BS: { iso3: "BHS", label: "Bahamas", lat: 25.38, lng: -77.99 },
  BH: { iso3: "BHR", label: "Bahrein", lat: null, lng: null },
  BD: { iso3: "BGD", label: "Bangladesh", lat: 23.56, lng: 90.38 },
  BB: { iso3: "BRB", label: "Barbados", lat: null, lng: null },
  BE: { iso3: "BEL", label: "Bélgica", lat: 50.5, lng: 4.34 },
  BZ: { iso3: "BLZ", label: "Belice", lat: 17.19, lng: -88.67 },
  BJ: { iso3: "BEN", label: "Benin", lat: 9.19, lng: 2.28 },
  BY: { iso3: "BLR", label: "Bielorrusia", lat: 53.74, lng: 27.95 },
  BO: { iso3: "BOL", label: "Bolivia", lat: -16.32, lng: -63.54 },
  BQ: { iso3: "BES", label: "Bonaire, San Eustaquio y Saba", lat: null, lng: null },
  BA: { iso3: "BIH", label: "Bosnia y Herzegovina", lat: 43.94, lng: 17.67 },
  BW: { iso3: "BWA", label: "Botswana", lat: -22.25, lng: 24.66 },
  BR: { iso3: "BRA", label: "Brasil", lat: -14.26, lng: -54.36 },
  BN: { iso3: "BRN", label: "Brunei Darussalam", lat: 4.73, lng: 114.83 },
  BG: { iso3: "BGR", label: "Bulgaria", lat: 42.73, lng: 25.47 },
  BF: { iso3: "BFA", label: "Burkina Faso", lat: 12.36, lng: -1.65 },
  BI: { iso3: "BDI", label: "Burundi", lat: -3.42, lng: 29.89 },
  BT: { iso3: "BTN", label: "Bután", lat: 27.51, lng: 90.46 },
  CV: { iso3: "CPV", label: "Cabo Verde", lat: null, lng: null },
  KH: { iso3: "KHM", label: "Camboya", lat: 12.53, lng: 104.98 },
  CM: { iso3: "CMR", label: "Camerún", lat: 7.29, lng: 12.25 },
  CA: { iso3: "CAN", label: "Canadá", lat: 62.45, lng: -96.82 },
  QA: { iso3: "QAT", label: "Catar", lat: 25.34, lng: 51.18 },
  TD: { iso3: "TCD", label: "Chad", lat: 15.42, lng: 18.71 },
  CL: { iso3: "CHL", label: "Chile", lat: -36.6, lng: -71.3 },
  CN: { iso3: "CHN", label: "China", lat: 35.83, lng: 104.35 },
  CY: { iso3: "CYP", label: "Chipre", lat: 34.87, lng: 33.13 },
  CO: { iso3: "COL", label: "Colombia", lat: 4.07, lng: -72.93 },
  KM: { iso3: "COM", label: "Comoras", lat: null, lng: null },
  CG: { iso3: "COG", label: "Congo", lat: -0.65, lng: 14.77 },
  CD: { iso3: "COD", label: "Congo (República Democrática del)", lat: -4, lng: 21.68 },
  CI: { iso3: "CIV", label: "Costa de Marfil", lat: 7.43, lng: -5.58 },
  CR: { iso3: "CRI", label: "Costa Rica", lat: 9.72, lng: -84.24 },
  HR: { iso3: "HRV", label: "Croacia", lat: 44.49, lng: 16.52 },
  CW: { iso3: "CUW", label: "Curaçao", lat: null, lng: null },
  DK: { iso3: "DNK", label: "Dinamarca", lat: 56.27, lng: 10.39 },
  DM: { iso3: "DMA", label: "Dominica", lat: null, lng: null },
  EC: { iso3: "ECU", label: "Ecuador", lat: -1.79, lng: -78.1 },
  EG: { iso3: "EGY", label: "Egipto", lat: 26.79, lng: 30.78 },
  SV: { iso3: "SLV", label: "El Salvador", lat: 13.79, lng: -88.91 },
  AE: { iso3: "ARE", label: "Emiratos Árabes Unidos", lat: 24.28, lng: 53.99 },
  ER: { iso3: "ERI", label: "Eritrea", lat: 15.23, lng: 39.7 },
  SK: { iso3: "SVK", label: "Eslovaquia", lat: 48.67, lng: 19.72 },
  SI: { iso3: "SVN", label: "Eslovenia", lat: 46.15, lng: 15.13 },
  ES: { iso3: "ESP", label: "España", lat: 39.85, lng: -3.18 },
  US: { iso3: "USA", label: "Estados Unidos", lat: 45.14, lng: -119.38 },
  EE: { iso3: "EST", label: "Estonia", lat: 58.54, lng: 25.74 },
  SZ: { iso3: "SWZ", label: "Esuatini", lat: -26.47, lng: 31.37 },
  ET: { iso3: "ETH", label: "Etiopía", lat: 9.19, lng: 40.37 },
  FJ: { iso3: "FJI", label: "Fiji", lat: -17.15, lng: 0 },
  PH: { iso3: "PHL", label: "Filipinas", lat: 12.04, lng: 121.86 },
  FI: { iso3: "FIN", label: "Finlandia", lat: 65.01, lng: 26.08 },
  FR: { iso3: "FRA", label: "Francia", lat: 46.26, lng: 2.48 },
  GA: { iso3: "GAB", label: "Gabón", lat: -0.83, lng: 11.61 },
  GM: { iso3: "GMB", label: "Gambia", lat: 13.5, lng: -15.34 },
  GE: { iso3: "GEO", label: "Georgia", lat: 42.31, lng: 43.3 },
  GS: { iso3: "SGS", label: "Georgia del Sur y las Islas Sandwich del Sur", lat: null, lng: null },
  GH: { iso3: "GHA", label: "Ghana", lat: 7.9, lng: -1.09 },
  GD: { iso3: "GRD", label: "Granada", lat: null, lng: null },
  GR: { iso3: "GRC", label: "Grecia", lat: 38.37, lng: 23.38 },
  GU: { iso3: "GUM", label: "Guam", lat: null, lng: null },
  GT: { iso3: "GTM", label: "Guatemala", lat: 15.78, lng: -90.23 },
  GG: { iso3: "GGY", label: "Guernsey", lat: null, lng: null },
  GN: { iso3: "GIN", label: "Guinea", lat: 9.95, lng: -11.48 },
  GW: { iso3: "GNB", label: "Guinea Bissau", lat: 11.83, lng: -15.19 },
  GQ: { iso3: "GNQ", label: "Guinea Ecuatorial", lat: 1.65, lng: 10.3 },
  GY: { iso3: "GUY", label: "Guyana", lat: 4.82, lng: -58.97 },
  HT: { iso3: "HTI", label: "Haití", lat: 18.97, lng: -73.04 },
  HM: { iso3: "HMD", label: "Heard e Islas McDonald", lat: null, lng: null },
  HN: { iso3: "HND", label: "Honduras", lat: 14.5, lng: -86.25 },
  HU: { iso3: "HUN", label: "Hungría", lat: 47.19, lng: 19.46 },
  IN: { iso3: "IND", label: "India", lat: 21.73, lng: 82.79 },
  ID: { iso3: "IDN", label: "Indonesia", lat: -2.44, lng: 118.16 },
  IQ: { iso3: "IRQ", label: "Iraq", lat: 33.24, lng: 43.68 },
  IE: { iso3: "IRL", label: "Irlanda", lat: 53.4, lng: -8.01 },
  IM: { iso3: "IMN", label: "Isla de Man", lat: null, lng: null },
  CX: { iso3: "CXR", label: "Isla de Navidad", lat: null, lng: null },
  NF: { iso3: "NFK", label: "Isla Norfolk", lat: null, lng: null },
  IS: { iso3: "ISL", label: "Islandia", lat: 65.01, lng: -18.97 },
  CC: { iso3: "CCK", label: "Islas Cocos (Keeling)", lat: null, lng: null },
  CK: { iso3: "COK", label: "Islas Cook", lat: null, lng: null },
  MP: { iso3: "MNP", label: "Islas Marianas del Norte", lat: null, lng: null },
  MH: { iso3: "MHL", label: "Islas Marshall", lat: null, lng: null },
  SB: { iso3: "SLB", label: "Islas Salomón", lat: -8.71, lng: 159.45 },
  UM: { iso3: "UMI", label: "Islas Ultramarinas Menores de los Estados Unidos", lat: null, lng: null },
  IL: { iso3: "ISR", label: "Israel", lat: 31.39, lng: 35.05 },
  IT: { iso3: "ITA", label: "Italia", lat: 41.87, lng: 12.62 },
  JM: { iso3: "JAM", label: "Jamaica", lat: 18.11, lng: -77.27 },
  JP: { iso3: "JPN", label: "Japón", lat: 38.29, lng: 137.48 },
  JE: { iso3: "JEY", label: "Jersey", lat: null, lng: null },
  JO: { iso3: "JOR", label: "Jordania", lat: 31.29, lng: 37.06 },
  KZ: { iso3: "KAZ", label: "Kazajistán", lat: 48.02, lng: 66.91 },
  KE: { iso3: "KEN", label: "Kenia", lat: 0.41, lng: 37.87 },
  KG: { iso3: "KGZ", label: "Kirguistán", lat: 41.29, lng: 74.86 },
  KI: { iso3: "KIR", label: "Kiribati", lat: null, lng: null },
  KW: { iso3: "KWT", label: "Kuwait", lat: 29.29, lng: 47.49 },
  LS: { iso3: "LSO", label: "Lesoto", lat: -29.65, lng: 28.16 },
  LV: { iso3: "LVA", label: "Letonia", lat: 56.79, lng: 24.62 },
  LB: { iso3: "LBN", label: "Líbano", lat: 33.87, lng: 35.87 },
  LR: { iso3: "LBR", label: "Liberia", lat: 6.45, lng: -9.49 },
  LY: { iso3: "LBY", label: "Libia", lat: 26.36, lng: 17.24 },
  LI: { iso3: "LIE", label: "Liechtenstein", lat: null, lng: null },
  LT: { iso3: "LTU", label: "Lituania", lat: 55.14, lng: 23.82 },
  LU: { iso3: "LUX", label: "Luxemburgo", lat: 49.79, lng: 5.96 },
  MK: { iso3: "MKD", label: "Macedonia del Norte", lat: 41.58, lng: 21.71 },
  MG: { iso3: "MDG", label: "Madagascar", lat: -18.82, lng: 46.87 },
  MY: { iso3: "MYS", label: "Malasia", lat: 3.85, lng: 109.63 },
  MW: { iso3: "MWI", label: "Malaui", lat: -13.02, lng: 34.23 },
  MV: { iso3: "MDV", label: "Maldivas", lat: null, lng: null },
  ML: { iso3: "MLI", label: "Malí", lat: 17.54, lng: -3.95 },
  MT: { iso3: "MLT", label: "Malta", lat: 35.95, lng: 14.37 },
  MA: { iso3: "MAR", label: "Marruecos", lat: 28.59, lng: -9.07 },
  MU: { iso3: "MUS", label: "Mauricio", lat: null, lng: null },
  MR: { iso3: "MRT", label: "Mauritania", lat: 21.01, lng: -10.99 },
  MX: { iso3: "MEX", label: "México", lat: 23.63, lng: -101.97 },
  FM: { iso3: "FSM", label: "Micronesia", lat: null, lng: null },
  MD: { iso3: "MDA", label: "Moldavia", lat: 46.98, lng: 28.32 },
  MC: { iso3: "MCO", label: "Mónaco", lat: null, lng: null },
  MN: { iso3: "MNG", label: "Mongolia", lat: 46.82, lng: 103.76 },
  ME: { iso3: "MNE", label: "Montenegro", lat: 42.7, lng: 19.39 },
  MZ: { iso3: "MOZ", label: "Mozambique", lat: -18.53, lng: 35.48 },
  MM: { iso3: "MMR", label: "Myanmar", lat: 19.13, lng: 96.74 },
  NA: { iso3: "NAM", label: "Namibia", lat: -22.99, lng: 18.41 },
  NR: { iso3: "NRU", label: "Nauru", lat: null, lng: null },
  NP: { iso3: "NPL", label: "Nepal", lat: 28.41, lng: 84.13 },
  NI: { iso3: "NIC", label: "Nicaragua", lat: 12.87, lng: -85.41 },
  NE: { iso3: "NER", label: "Níger", lat: 17.57, lng: 8.1 },
  NG: { iso3: "NGA", label: "Nigeria", lat: 9.05, lng: 8.63 },
  NU: { iso3: "NIU", label: "Niue", lat: null, lng: null },
  NO: { iso3: "NOR", label: "Noruega", lat: 69.37, lng: 18.14 },
  NC: { iso3: "NCL", label: "Nueva Caledonia", lat: -21.25, lng: 165.57 },
  NZ: { iso3: "NZL", label: "Nueva Zelanda", lat: -40.55, lng: 172.51 },
  OM: { iso3: "OMN", label: "Omán", lat: 21.52, lng: 55.9 },
  NL: { iso3: "NLD", label: "Países Bajos", lat: 52.16, lng: 5.2 },
  PK: { iso3: "PAK", label: "Pakistán", lat: 30.41, lng: 69.36 },
  PW: { iso3: "PLW", label: "Palau", lat: null, lng: null },
  PA: { iso3: "PAN", label: "Panamá", lat: 8.42, lng: -80.1 },
  PG: { iso3: "PNG", label: "Papua Nueva Guinea", lat: -6.58, lng: 148.51 },
  PY: { iso3: "PRY", label: "Paraguay", lat: -23.45, lng: -58.49 },
  PE: { iso3: "PER", label: "Perú", lat: -9.2, lng: -75.04 },
  PN: { iso3: "PCN", label: "Pitcairn", lat: null, lng: null },
  PF: { iso3: "PYF", label: "Polinesia Francesa", lat: null, lng: null },
  PL: { iso3: "POL", label: "Polonia", lat: 51.94, lng: 19.05 },
  PT: { iso3: "PRT", label: "Portugal", lat: 39.56, lng: -7.96 },
  GB: { iso3: "GBR", label: "Reino Unido", lat: 54.3, lng: -2.95 },
  SY: { iso3: "SYR", label: "República Árabe Siria", lat: 34.77, lng: 39.03 },
  CF: { iso3: "CAF", label: "República Centroafricana", lat: 6.71, lng: 20.92 },
  CZ: { iso3: "CZE", label: "República Checa", lat: 49.84, lng: 15.55 },
  KR: { iso3: "KOR", label: "República de Corea", lat: 36.5, lng: 127.79 },
  LA: { iso3: "LAO", label: "República Democrática Popular de Lao", lat: 18.17, lng: 103.84 },
  DO: { iso3: "DOM", label: "República Dominicana", lat: 18.74, lng: -70.13 },
  RW: { iso3: "RWA", label: "Ruanda", lat: -2.03, lng: 29.92 },
  RO: { iso3: "ROU", label: "Rumanía", lat: 45.95, lng: 24.92 },
  RU: { iso3: "RUS", label: "Rusia", lat: 61.2, lng: 0 },
  BL: { iso3: "BLM", label: "Saint Barthélemy", lat: null, lng: null },
  KN: { iso3: "KNA", label: "Saint Kitts y Nevis", lat: null, lng: null },
  MF: { iso3: "MAF", label: "Saint Martin (francesa)", lat: null, lng: null },
  WS: { iso3: "WSM", label: "Samoa", lat: null, lng: null },
  AS: { iso3: "ASM", label: "Samoa Americana", lat: null, lng: null },
  SM: { iso3: "SMR", label: "San Marino", lat: null, lng: null },
  PM: { iso3: "SPM", label: "San Pedro y Miquelón", lat: null, lng: null },
  VC: { iso3: "VCT", label: "San Vicente y las Granadinas", lat: null, lng: null },
  SH: { iso3: "SHN", label: "Santa Helena, Ascensión y Tristán de Acuña", lat: null, lng: null },
  LC: { iso3: "LCA", label: "Santa Lucía", lat: null, lng: null },
  VA: { iso3: "VAT", label: "Santa Sede", lat: null, lng: null },
  ST: { iso3: "STP", label: "Santo Tomé y Príncipe", lat: null, lng: null },
  SN: { iso3: "SEN", label: "Senegal", lat: 14.47, lng: -14.55 },
  RS: { iso3: "SRB", label: "Serbia", lat: 44.21, lng: 20.91 },
  SC: { iso3: "SYC", label: "Seychelles", lat: null, lng: null },
  SL: { iso3: "SLE", label: "Sierra Leona", lat: 8.42, lng: -11.74 },
  SG: { iso3: "SGP", label: "Singapur", lat: null, lng: null },
  SX: { iso3: "SXM", label: "Sint Maarten (neerlandesa)", lat: null, lng: null },
  SO: { iso3: "SOM", label: "Somalia", lat: 5.17, lng: 46.06 },
  LK: { iso3: "LKA", label: "Sri Lanka", lat: 7.9, lng: 80.74 },
  ZA: { iso3: "ZAF", label: "Sudáfrica", lat: -28.46, lng: 24.59 },
  SD: { iso3: "SDN", label: "Sudán", lat: 15.31, lng: 30.17 },
  SS: { iso3: "SSD", label: "Sudán del Sur", lat: 7.88, lng: 29.59 },
  SE: { iso3: "SWE", label: "Suecia", lat: 62.23, lng: 17.47 },
  CH: { iso3: "CHE", label: "Suiza", lat: 46.8, lng: 8.23 },
  SR: { iso3: "SUR", label: "Suriname", lat: 3.92, lng: -56 },
  TH: { iso3: "THA", label: "Tailandia", lat: 13.05, lng: 101.48 },
  TZ: { iso3: "TZA", label: "Tanzania", lat: -6.34, lng: 34.83 },
  TJ: { iso3: "TJK", label: "Tayikistán", lat: 38.85, lng: 71.21 },
  TF: { iso3: "ATF", label: "Tierras Australes Francesas", lat: -49.2, lng: 69.64 },
  TL: { iso3: "TLS", label: "Timor-Leste", lat: -8.83, lng: 126.15 },
  TG: { iso3: "TGO", label: "Togo", lat: 8.47, lng: 0.91 },
  TK: { iso3: "TKL", label: "Tokelau", lat: null, lng: null },
  TO: { iso3: "TON", label: "Tonga", lat: null, lng: null },
  TT: { iso3: "TTO", label: "Trinidad y Tobago", lat: 10.45, lng: -61.42 },
  TN: { iso3: "TUN", label: "Túnez", lat: 33.83, lng: 9.51 },
  TM: { iso3: "TKM", label: "Turkmenistán", lat: 39.01, lng: 59.52 },
  TR: { iso3: "TUR", label: "Turquía", lat: 38.98, lng: 35.42 },
  TV: { iso3: "TUV", label: "Tuvalu", lat: null, lng: null },
  UA: { iso3: "UKR", label: "Ucrania", lat: 48.35, lng: 31.08 },
  UG: { iso3: "UGA", label: "Uganda", lat: 1.4, lng: 32.31 },
  UY: { iso3: "URY", label: "Uruguay", lat: -32.53, lng: -55.82 },
  UZ: { iso3: "UZB", label: "Uzbekistán", lat: 41.37, lng: 64.49 },
  VU: { iso3: "VUT", label: "Vanuatu", lat: -15.61, lng: 167.24 },
  VE: { iso3: "VEN", label: "Venezuela", lat: 6.44, lng: -66.53 },
  VN: { iso3: "VNM", label: "Vietnam", lat: 15.98, lng: 105.75 },
  WF: { iso3: "WLF", label: "Wallis y Futuna", lat: null, lng: null },
  YE: { iso3: "YEM", label: "Yemen", lat: 15.79, lng: 47.86 },
  DJ: { iso3: "DJI", label: "Yibuti", lat: 11.81, lng: 42.49 },
  ZM: { iso3: "ZMB", label: "Zambia", lat: -13.1, lng: 27.69 },
  ZW: { iso3: "ZWE", label: "Zimbabue", lat: -18.89, lng: 29.06 },
};

export type PaisSegmentable = {
  iso2: string;
  iso3: string;
  label: string;
  lat: number | null;
  lng: number | null;
};

export const PAISES_SEGMENTABLES: PaisSegmentable[] = Object.keys(
  GOOGLE_GEO_TARGET_IDS,
)
  .filter((iso2) => METADATA[iso2])
  .map((iso2) => ({ iso2, ...METADATA[iso2] }));

export function paisSegmentablePorIso2(iso2: string): PaisSegmentable | null {
  return PAISES_SEGMENTABLES.find((p) => p.iso2 === iso2) ?? null;
}

export const RADIO_POR_DEFECTO_KM = 10;

/** Dónde vive el GeoJSON de fronteras (fuente: johan/world.geo.json, ISO
 * alfa-3 en `feature.id`, ~250 KB). Se sirve como archivo estático, no se
 * agrupa en el bundle de la app. */
export const WORLD_COUNTRIES_GEOJSON_URL = "/geo/world-countries.json";
